
homepage:
    pattern:  /article/{page}
    defaults: { _controller: tutoWelcomeBundle:Homepage:index, page : 1 }
    requirements :
      page : \d+
      _method : GET
whoami:
  pattern: /whoami/{nom}
  defaults: { _controller: tutoWelcomeBundle:Homepage:whoAmI, nom : ''}
  requirements :
    page : \w+
contact:
  pattern: /contact
  defaults: { _controller: tutoWelcomeBundle:Contact:index}

